// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{METHOD_ELF, METHOD_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::time::Instant;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Benchmark parameters
    let data_sizes: Vec<usize> = vec![64, 128, 256, 512, 1024, 2048];
    let num_hashes_per_proof: Vec<u32> = vec![1, 2, 4, 8, 16, 32];

    // Obtain the default prover (reuse for all benchmarks)
    let prover = default_prover();

    println!("BLAKE3 ZK Proof Benchmark");
    println!("=========================\n");
    println!("{:>10} | {:>12} | {:>12} | {:>15}", "Data Size", "Num Hashes", "Prove Time", "Total Cycles");
    println!("{:-<10}-+-{:-<12}-+-{:-<12}-+-{:-<15}", "", "", "", "");

    let mut sum_weights: f64 = 0.0;
    let mut weighted_sum: f64 = 0.0;

    for &data_size in &data_sizes {
        for &num_hashes in &num_hashes_per_proof {
            // Generate random-ish data of the specified size
            let data: Vec<u8> = (0..data_size).map(|i| (i % 256) as u8).collect();

            // Build the executor environment
            let env = ExecutorEnv::builder()
                .write(&data)
                .unwrap()
                .write(&num_hashes)
                .unwrap()
                .build()
                .unwrap();

            // Measure proving time
            let start = Instant::now();
            let prove_info = prover.prove(env, METHOD_ELF).unwrap();
            let prove_duration = start.elapsed();

            // Extract and verify the receipt
            let receipt = prove_info.receipt;
            receipt.verify(METHOD_ID).unwrap();

            // Get the output hashes
            let output_hashes: Vec<[u8; 32]> = receipt.journal.decode().unwrap();
            assert_eq!(output_hashes.len(), num_hashes as usize);

            // Verify each hash matches expected
            for i in 0..num_hashes {
                let mut input = data.clone();
                input.extend_from_slice(&i.to_le_bytes());
                let expected = blake3::hash(&input);
                assert_eq!(output_hashes[i as usize], *expected.as_bytes());
            }

            let total_cycles = prove_info.stats.total_cycles;

            // Calculate throughput for weighted average
            let size_float = (data_size * num_hashes as usize) as f64;
            let throughput = size_float / prove_duration.as_secs_f64();
            weighted_sum += size_float * throughput;
            sum_weights += size_float;

            println!(
                "{:>10} | {:>12} | {:>10.2}s | {:>15}",
                data_size,
                num_hashes,
                prove_duration.as_secs_f64(),
                total_cycles
            );
        }
    }

    let avg_throughput = weighted_sum / sum_weights;
    println!("\nAverage throughput: {} bytes/s", avg_throughput as usize);
    println!("Benchmark complete!");
}
