name: ci

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build risc0.nix
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake check
      - run: nix build .#risc0-toolchain --print-out-paths
      - run: nix build .#cargo-risczero --print-out-paths
      - run: nix build .#risc0-cpp-toolchain --print-out-paths
      - run: nix build .#risc0-home --print-out-paths

  test:
    name: Test template dev shell
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./templates/hello-world -> target"
      - name: Replace risc0.nix URL with local path
        run: |
          sed -i 's|url = "github:argumentcomputer/risc0.nix"|url = "path:../.."|' flake.nix
          head -n 20 flake.nix
          nix flake update risc0
        working-directory: ${{ github.workspace }}/templates/hello-world
      - run: nix develop --command bash -c "cargo run"
        working-directory: ${{ github.workspace }}/templates/hello-world
